version: '3'

volumes:
  pg_kittygram_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env    
    volumes:
      - pg_kittygram_data:/var/lib/postgresql/data
  backend:
    image: crossmos/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    image: crossmos/kittygram_frontend
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: crossmos/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
